commonProperties:
  env:
    accountId:
      dev: 730335273876
      hom: 1234567890
      prod: 1234567890
    tags:
      A: B
      B: D
    awsglue:
      version: "4.0"
      language: "python"
      workerType: "G.1X"
      autoScaling: false
      connectivity:
        - subnet1
        - subnet2
        - subnet3
      securityGroup:
        - sg-123456789
        - sg-234567891
        - sg-345678912
    awslambda:
      identifier: "python3.10" 
      architecture: "x86_64"
      enableVPC: true
      vpc_name: "vpc_account" 
      subnets:  
        - subnet1 
        - subnet2 
        - subnet3 
      securityGroups: 
        - sg-123456789 
        - sg-234567891 
        - sg-345678912 

# melhorar experiencia no sentido operacional (ex falhou rotina, pode dar um restart, é idepotente, etc...) 
# descritivo da rotina e qual o procedimento no caso de falha? 

environments:
  dev:
    runtimes: 
      - jobName: "pix-sor-ingestion" 
        tags:  
          A: var 
          B: var 
        compute: 
          type: awsglue 
          scriptLocation: "s3://dataplanegluejobscripts/scripts/myconvertionjob.py"  
          maxNumberOfWorkers: 2
          maximumParallelExecutions: 1
          maxExecutionTime: 30
        security: 
          executionRoleArn: "arn:aws:iam::730335273876:role/dataplanegluejobrole" 

      # - jobName: "pix-sot-ingestion" 
      #   tags:  
      #     A: var 
      #     B: var 
      #   compute: 
      #     type: awsglue 
      #     scriptLocation: "s3://dataplanegluejobscripts/scripts/pixsotingestion.py"  
      #     maxNumberOfWorkers: 30 
      #     maximumParallelExecutions: 2 
      #     maxExecutionTime: 120 
      #   security: 
      #     executionRoleArn: "arn:aws:iam::730335273876:role/dataplanegluejobrole" 

schedulerRoutine: 
  name: JP700002 
  dependsOn: JP700001 
  cron: "0 6 * * *" 
  workflow: 
    - pix-sor-ingestion 
    # - pix-sot-ingestion 